version: "3.8"

services:
  backend:
    image: gaeun919/book-recommendation-backend:latest
    restart: always
    volumes:
      - ./data:/app/data
      - ./chroma_books:/app/chroma_books
      - ./chroma_history:/app/chroma_history
      - ./chroma_prefs:/app/chroma_prefs

  nginx:
    image: gaeun919/book-recommendation-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
